file="ellipse.cpp"

compile: 
	# g++ main.cpp -o main `pkg-config --cflags --libs opencv4`
	g++ $(file) -o output -I/path/to/opencv/include -L/path/to/opencv/lib -lopencv_core -lopencv_highgui -lopencv_imgproc
